image:
  repository: passbolt/passbolt
  pullPolicy: IfNotPresent
  tag: 4.8.0-1-ce-non-root

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

passboltConfig:
  appUrl: ''
  additionalEnvs: []

passboltNetwork:
  webPort: 30097
  certificateID:
  hostNetwork: false

passboltStorage:
  gpg:
    type: ixVolume
    datasetName: gpg
  jwt:
    type: ixVolume
    ixVolumeConfig:
      datasetName: jwt
  mariadbData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: mariadbData
  mariadbBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: mariadbBackup
  additionalStorages: []

notes:
  custom: |
    ## Register admin user

    Connect to the container's shell and run the following command replacing the
    values (`user@example.com`, `first_name`, `last_name`) with your own values.

    ```shell
    /usr/share/php/passbolt/bin/cake passbolt register_user -r admin \
      -u user@example.com -f first_name -l last_name
    ```
