image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: '7.6'

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

pgadminConfig:
  adminEmail: ''
  adminPassword: ''
  additionalEnvs: []

pgadminNetwork:
  webPort: 30056
  certificateID:
  hostNetwork: false

pgadminStorage:
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []
