image:
  repository: ghcr.io/ajnart/homarr
  pullPolicy: IfNotPresent
  tag: 0.15.3

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

homarrConfig:
  password: ''
  additionalEnvs: []

homarrNetwork:
  webPort: 30052
  hostNetwork: false

homarrRunAs:
  user: 568
  group: 568

homarrStorage:
  configs:
    type: ixVolume
    ixVolumeConfig:
      datasetName: configs
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  icons:
    type: ixVolume
    ixVolumeConfig:
      datasetName: icons
  additionalStorages: []
