image:
  repository: vikunja/vikunja
  pullPolicy: IfNotPresent
  tag: 0.24.5

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

vikunjaConfig:
  url: ''
  maxFileSize: 20
  additionalEnvs: []

vikunjaRunAs:
  user: 568
  group: 568

vikunjaNetwork:
  webPort: 31002

vikunjaStorage:
  additionalStorages: []
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `vikunja`
      - Username: `vikunja`
      - Password: `{{ .Values.vikunjaDbPass }}`
      - Host:     `{{ .Values.vikunjaDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "vikunjaDbPass" }}
    {{- $_ := unset .Values "vikunjaDbHost" }}
