image:
  repository: castopod/app
  pullPolicy: IfNotPresent
  tag: 1.12.3
webImage:
  repository: castopod/web-server
  pullPolicy: IfNotPresent
  tag: 1.12.3

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

castopodConfig:
  baseUrl: http://localhost:30085
  webTimeout: 900
  webMaxBodySize: 512
  phpMemoryLimit: 512
  enable2fa: false
  disableHttpsRedirect: true
  additionalEnvs: []

castopodNetwork:
  webPort: 30085

castopodStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  mariadbData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: mariadbData
  mariadbBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: mariadbBackup
  additionalStorages: []
