image:
  pullPolicy: IfNotPresent
  repository: collabora/code
  tag: 24.04.5.1.1
nginxImage:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: 1.23.3

collaboraConfig:
  enableWebUI: true
  username: ''
  password: ''
  aliasGroup1: []
  dictionaries: []
  extraParams:
    - --o:welcome.enable=false
    - --o:user_interface.mode=notebookbar
    - --o:ssl.termination=true
    - --o:ssl.enable=false
    - --o:net.proto=IPv4
    - --o:logging.level=warning
    - --o:logging.level_startup=warning
    - --o:mount_jail_tree=false
  serverName: ''
  additionalEnvs: []

collaboraNetwork:
  webPort: 31020
  certificateID:

collaboraStorage:
  additionalStorages: []
