node18Image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-18
node18MinimalImage:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-18-minimal
node16Image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-16
node16MinimalImage:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-16-minimal
node14Image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-14
node14MinimalImage:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: 3.1.9-14-minimal

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

noderedConfig:
  imageSelector: node16Image
  safeMode: false
  enableProjects: false
  additionalEnvs: []

noderedNetwork:
  webPort: 30049
  hostNetwork: false

noderedStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
