image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

controllers:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

registry: quay.io
user: user
pass: secret_pass
email: mail@example.com

imagePullSecrets:
  image-secret-name:
    enabled: true
    labels: {}
    annotations: {}
    data:
      registry: "{{ .Values.registry }}"
      username: "{{ .Values.user }}"
      password: "{{ .Values.pass }}"
      email: "{{ .Values.email }}"
    # TODO: Add support for targetSelector
    # targetSelector: all
