image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

workload:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"


registry: quay.io
user: user
pass: secret_pass
email: mail@example.com

imagePullSecret:
  image-secret-name:
    enabled: true
    labels: {}
    annotations: {}
    data:
      registry: "{{ .Values.registry }}"
      username: "{{ .Values.user }}"
      password: "{{ .Values.pass }}"
      email: "{{ .Values.email }}"
