j8Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.1-java8
j8gceImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.1-java8-graalvm-ce
j8j9Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.1-java8-openj9
j8jdkImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.1-java8-jdk
j11Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.0-java11
j11j9Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.2.2-java11-openj9
j11jdkImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.4.0-java11-jdk
j17Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.0-java17
j17j9Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.2.2-java17-openj9
j17jdkImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.0-java17-jdk
j17gceImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2023.8.3-java17-graalvm-ce
j17alpineImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.6.0-java17-alpine
j19Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2023.3.0-java19
j21Image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.4.1-java21
j21gImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.4.1-java21-graalvm
j21alpineImage:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: 2024.4.1-java21-alpine

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

mcConfig:
  eula: false
  imageSelector: j21Image
  version: LATEST
  type: VANILLA
  serverName: Minecraft Server
  seed: ''
  mode: survival
  levelType: minecraft:default
  difficulty: easy
  pvp: true
  motd: Welcome to Minecraft on TrueNAS!
  enableRcon: false
  rconPassword: ''
  maxPlayers: 20
  maxWorldSize: 10000
  allowNether: true
  announcePlayerAchievements: true
  enableCommandBlock: false
  forceGameMode: false
  generateStructures: true
  hardcore: false
  maxBuildHeight: 256
  spawnAnimals: true
  spawnMonsters: true
  spawnNpcs: true
  spawnProtection: 16
  viewDistance: 10
  allowFlight: false
  onlineMode: true
  maxTickTime: 60000
  ops: []
  whitelist: []
  additionalEnvs: []
mcID:
  user: 568
  group: 568
mcNetwork:
  hostNetwork: false
  serverPort: 25565
  rconPort: 25575
mcStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
