image:
  repository: clamav/clamav
  pullPolicy: IfNotPresent
  tag: '1.0.1'

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

clamavConfig:
  disableClamd: false
  disableFreshClamd: false
  disableMilterd: true
  clamdStartupTimeout: 1800
  freshclamChecks: 1
  additionalEnvs: []

clamavNetwork:
  clamdPort: 30000
  milterdPort: 30001

clamavStorage:
  sigdb:
    type: ixVolume
    hostPath: ''
    datasetName: sig-db
  scandir:
    type: ixVolume
    hostPath: ''
    datasetName: scan-dir
