image:
  repository: zerotier/zerotier
  pullPolicy: IfNotPresent
  tag: 1.14.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

zerotierConfig:
  authToken: ''
  identityPublic: ''
  identitySecret: ''
  networks: []
  additionalEnvs: []

zerotierNetwork:
  hostNetwork: false

zerotierStorage:
  additionalStorages: []
