image:
  repository: ghcr.io/ep1cman/unifi-protect-backup
  pullPolicy: IfNotPresent
  tag: 0.11.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

upbConfig:
  unifiProtectUsername: ''
  unifiProtectPassword: ''
  unifiProtectAddress: ''
  unifiProtectPort: 443
  unifiProtectVerifySsl: true
  skipMissing: false
  ignoreCameras: []
  detectionTypes:
    - motion
    - person
    - vehicle
    - ring
  rcloneDestination: ''
  rcloneArgs: []
  rclonePurgeArgs: []
  additionalEnvs: []

upbID:
  user: 568
  group: 568

upbStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
