image:
  repository: ghcr.io/gethomepage/homepage
  pullPolicy: IfNotPresent
  tag: v0.9.3

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

homepageConfig:
  additionalEnvs: []

homepageNetwork:
  webPort: 30054
  hostNetwork: false

homepageStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
