image:
  repository: minio/minio
  tag: RELEASE.2023-04-07T05-28-58Z
  pullPolicy: IfNotPresent

logsearchImage:
  repository: minio/operator
  tag: v4.5.8
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

minioCreds:
  rootUser: ''
  rootPass: ''

minioRunAs:
  user: 568
  group: 568

minioNetwork:
  apiPort: 30000
  webPort: 30001
  certificateID: ''
  hostNetwork: false
  serverUrl: ''
  consoleUrl: ''

minioMultiMode: []

minioStorage: []

minioLogging:
  anonymous: false
  quiet: false

  logsearch:
    enabled: false
    diskCapacityGB: 5
    pgData:
      type: ixVolume
      hostPath: ''
      datasetName: postgres-data
    pgBackup:
      type: ixVolume
      hostPath: ''
      datasetName: postgres-backup
