name: emby
description: Emby is designed to help you manage your personal media library, such
  as home videos and photos
annotations:
  title: Emby Server
type: application
version: 2.0.11
apiVersion: v2
appVersion: 4.8.8.0
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://emby.media/
icon: https://media.sys.truenas.net/apps/emby/icons/icon.png
sources:
  - https://emby.media/
  - https://hub.docker.com/r/emby/embyserver
  - https://github.com/truenas/charts/tree/master/charts/emby
keywords:
  - emby
  - media
