image:
  repository: netbootxyz/netbootxyz
  pullPolicy: IfNotPresent
  tag: 0.7.4-nbxyz2

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

netbootConfig:
  tftpdOpts: []
  additionalEnvs: []

netbootNetwork:
  # TFTP only works with hostNetwork: true
  hostNetwork: true
  tftpPort: 31009
  webHttpPort: 31010
  webAssetsPort: 31011

netbootStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  assets:
    type: ixVolume
    ixVolumeConfig:
      datasetName: assets
  additionalStorages: []
