image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: 1.31.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

vaultwardenConfig:
  adminToken: ''
  additionalEnvs: []

vaultwardenNetwork:
  webPort: 30032
  wsEnabled: true
  wsPort: 30033
  hostNetwork: false
  certificateID:
  domain: ''

vaultwardenRunAs:
  user: 568
  group: 568

vaultwardenStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `vaultwarden`
      - Username: `vaultwarden`
      - Password: `{{ .Values.vaultwardenDbPass }}`
      - Host:     `{{ .Values.vaultwardenDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "vaultwardenDbPass" }}
    {{- $_ := unset .Values "vaultwardenDbHost" }}
