ddnsStorage:
  data:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/data

# This disables probes.
# As we can't have for each provider
# an api key, we just run through CI
# for the linting.
ci: true

ddnsConfig:
  config:
    - provider: selfhost.de
      host: "@"
      domain: example.com
      ipVersion: ""
      selfhostdeUsername: 123456
      selfhostdePassword: password
      selfhostdeProviderIP: true
    - provider: selfhost.de
      host: "@"
      domain: example.com
      ipVersion: ""
      selfhostdeUsername: username
      selfhostdePassword: password
      selfhostdeProviderIP: false
