name: grafana
description: Grafana is the open source analytics & monitoring solution for every
  database.
annotations:
  title: Grafana
type: application
version: 1.0.16
apiVersion: v2
appVersion: 10.1.5
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.1.1
home: https://grafana.com
icon: https://www.gravatar.com/avatar/31cea69afa424609b2d83621b4d47f1d?s=120&r=g&d=404
sources:
  - https://hub.docker.com/r/grafana/grafana
  - https://github.com/truenas/charts/tree/master/community/grafana
  - https://github.com/grafana
keywords:
  - dashboard
  - monitoring
  - analytics
  - metrics
