image:
  repository: freshrss/freshrss
  pullPolicy: IfNotPresent
  tag: 1.24.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

freshrssConfig:
  defaultAdmin: ''
  defaultAdminPass: ''
  enableCron: false
  # */20 * * * * = every 20 minutes (Recommended)
  cronSchedule: ''
  additionalEnvs: []

freshrssNetwork:
  webPort: 31000
  hostNetwork: false

freshrssStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  extensions:
    type: ixVolume
    ixVolumeConfig:
      datasetName: extensions
  additionalStorages: []
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `freshrss`
      - Username: `freshrss`
      - Password: `{{ .Values.freshrssDbPass }}`
      - Host:     `{{ .Values.freshrssDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "freshrssDbPass" }}
    {{- $_ := unset .Values "freshrssDbHost" }}
