image:
  repository: altran1502/immich-server
  pullPolicy: IfNotPresent
  tag: v1.108.0

mlImage:
  repository: altran1502/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.108.0

mlCudaImage:
  repository: altran1502/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.108.0-cuda

mlOpenvinoImage:
  repository: altran1502/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.108.0-openvino

pgvectorImage:
  repository: tensorchord/pgvecto-rs
  pullPolicy: IfNotPresent
  tag: pg15-v0.2.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

immichGPU: {}

immichConfig:
  publicLoginMessage: ''
  enableML: true
  mlImageType: mlImage
  logLevel: log
  huggingFaceEndpoint: ''

immichNetwork:
  webuiPort: 30041
  # Not user configurable, will be hidden on UI
  # Putting it here in case it needs to be configurable
  # in the future.
  machinelearningPort: 32002

immichStorage:
  uploads:
    type: ixVolume
    ixVolumeConfig:
      datasetName: uploads
  library:
    type: ixVolume
    ixVolumeConfig:
      datasetName: library
  thumbs:
    type: ixVolume
    ixVolumeConfig:
      datasetName: thumbs
  profile:
    type: ixVolume
    ixVolumeConfig:
      datasetName: profile
  video:
    type: ixVolume
    ixVolumeConfig:
      datasetName: video
  additionalLibraries: []
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `immich`
      - Username: `immich`
      - Password: `{{ .Values.immichDbPass }}`
      - Host:     `{{ .Values.immichDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "immichDbPass" }}
    {{- $_ := unset .Values "immichDbHost" }}
