image:
  pullPolicy: IfNotPresent
  repository: pihole/pihole
  tag: 2025.02.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

podOptions:
  dnsConfig:
    options: []

piholeConfig:
  webPassword: ''
  additionalEnvs: []

piholeNetwork:
  webPort: 20489
  interfaceName: ''
  dhcp:
    enabled: false
    start: ''
    end: ''
    gateway: ''

piholeStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  dnsmasq:
    type: ixVolume
    ixVolumeConfig:
      datasetName: dnsmasq
  additionalStorages: []
