name: prometheus
description: The Prometheus monitoring system and time series database.
annotations:
  title: Prometheus
type: application
version: 1.1.1
apiVersion: v2
appVersion: v2.48.1
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.4
home: https://prometheus.io
icon: https://media.sys.truenas.net/apps/prometheus/icons/icon.png
sources:
  - https://github.com/prometheus/prometheus
  - https://github.com/truenas/charts/tree/master/charts/prometheus
  - https://prometheus.io
keywords:
  - metrics
  - prometheus
