image:
  repository: gitea/gitea
  pullPolicy: IfNotPresent
  tag: 1.22.1-rootless

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

giteaConfig:
  additionalEnvs: []

giteaNetwork:
  webPort: 30008
  sshPort: 30009
  certificateID:
  rootURL: ''
  hostNetwork: false

# FIXME: Currently only user 1000 works.
# Any other uid is not mapped to the internal "git" user.
# https://github.com/go-gitea/gitea/issues/23632
giteaRunAs:
  user: 1000
  group: 1000

giteaStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `gitea`
      - Username: `gitea`
      - Password: `{{ .Values.giteaDbPass }}`
      - Host:     `{{ .Values.giteaDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "giteaDbPass" }}
    {{- $_ := unset .Values "giteaDbHost" }}
