plexNetwork:
  webPort: 31000

plexStorage:
  data:
    type: pvc
  config:
    type: pvc
  transcode:
    type: emptyDir
    emptyDirConfig:
      medium: ""
      size: ""
  additionalStorages:
  - type: pvc
    mountPath: /action_movies
  - type: pvc
    mountPath: /adventure_movies
