image:
  repository: filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: v2.30.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

filebrowserConfig:
  additionalEnvs: []

filebrowserNetwork:
  webPort: 30044
  certificateID:
  hostNetwork: false

filebrowserRunAs:
  user: 568
  group: 568

filebrowserStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []

notes:
  custom: |
    Default credentials:
    -  username: admin
    -  password: admin
