name: home-assistant
description: Home Assistant App for TrueNAS SCALE
annotations:
  title: Home Assistant
type: application
version: 1.0.114
apiVersion: v2
appVersion: 2023.10.3
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://github.com/home-assistant/home-assistant
icon: https://avatars.githubusercontent.com/u/13844975?s=200&v=4
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/truenas/charts/tree/master/charts/home-assistant
keywords:
  - home-automation
