name: home-assistant
description: Home Assistant App for TrueNAS SCALE
annotations:
  title: Home Assistant
type: application
version: 1.0.72
apiVersion: v2
appVersion: '2023.3.5'
kubeVersion: '>=1.16.0-0'
maintainers:
- name: truenas
  url: https://www.truenas.com/
dependencies:
- name: common
  repository: file://../../../common/2207.0.0
  version: 2207.0.0
home: https://github.com/home-assistant/home-assistant
icon: https://avatars.githubusercontent.com/u/13844975?s=200&v=4
sources:
- https://github.com/home-assistant/home-assistant
- https://github.com/truenas/charts/tree/master/library/ix-dev/charts/home-assistant
keywords:
- home-automation
