image:
  pullPolicy: IfNotPresent
  repository: homeassistant/home-assistant
  tag: 2024.7.2

# Keep using the same image
# as before the migration
haPostgresImage:
  pullPolicy: IfNotPresent
  repository: postgres
  tag: '13.1'

yqImage:
  pullPolicy: IfNotPresent
  repository: mikefarah/yq
  tag: 4.40.5

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

podOptions:
  dnsConfig:
    options: []

haConfig:
  allowDevices: false
  additionalEnvs: []

haNetwork:
  webPort: 20810
  hostNetwork: false

haID:
  user: 568
  group: 568

haStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  media:
    type: ixVolume
    ixVolumeConfig:
      datasetName: media
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `{{ .Values.haDbName }}`
      - Username: `{{ .Values.haDbUser }}`
      - Password: `{{ .Values.haDbPass }}`
      - Host:     `{{ .Values.haDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "haDbUser" }}
    {{- $_ := unset .Values "haDbName" }}
    {{- $_ := unset .Values "haDbPass" }}
    {{- $_ := unset .Values "haDbHost" }}
