image:
  repository: listmonk/listmonk
  pullPolicy: IfNotPresent
  tag: v3.0.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

listmonkConfig:
  adminUsername: ''
  adminPassword: ''
  additionalEnvs: []

listmonkNetwork:
  webPort: 30093
  hostNetwork: false

listmonkRunAs:
  user: 568
  group: 568

listmonkStorage:
  uploads:
    type: ixVolume
    ixVolumeConfig:
      datasetName: uploads
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `listmonk`
      - Username: `listmonk`
      - Password: `{{ .Values.listmonkDbPass }}`
      - Host:     `{{ .Values.listmonkDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "listmonkDbPass" }}
    {{- $_ := unset .Values "listmonkDbHost" }}
