image:
  repository: ghcr.io/advplyr/audiobookshelf
  pullPolicy: IfNotPresent
  tag: 2.11.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

audiobookshelfConfig:
  additionalEnvs: []
audiobookshelfNetwork:
  webPort: 30067
  hostNetwork: false
audiobookshelfRunAs:
  user: 568
  group: 568
audiobookshelfStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  metadata:
    type: ixVolume
    ixVolumeConfig:
      datasetName: metadata
  additionalStorages: []
