image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  tag: v2.53.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

prometheusConfig:
  retentionTime: 15d
  retentionSize: ''
  walCompression: true
  additionalEnvs: []
  additionalArgs: []

prometheusNetwork:
  apiPort: 30002
  hostNetwork: false

prometheusRunAs:
  user: 568
  group: 568

prometheusStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
