image:
  repository: syncthing/syncthing
  tag: '1.27.6'
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

syncthingConfig:
  additionalEnvs: []
  # Currently not exposed in the UI
  # But can be exposed in the future
  natTraversal: false
  localDiscovery: false
  globalDiscovery: false
  telemetry: false
  relaying: false
  announceLANAddresses: false

syncthingID:
  user: 568
  group: 568

syncthingNetwork:
  webPort: 30000
  certificateID: null
  hostNetwork: true
  # Only used if hostNetwork is false
  localDiscoveryPort: 21027
  tcpPort: 22000
  quicPort: 22000

syncthingStorage:
  home:
    type: ixVolume
    ixVolumeConfig:
      datasetName: home
  additionalStorages: []
