image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.9.7

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

jellyfinConfig:
  publishedServerUrl: ''
  additionalEnvs: []

jellyfinGPU: {}

jellyfinNetwork:
  webPort: 30013
  hostNetwork: false

jellyfinRunAs:
  user: 568
  group: 568

jellyfinStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  cache:
    type: ixVolume
    ixVolumeConfig:
      datasetName: cache
  transcodes:
    type: ixVolume
    ixVolumeConfig:
      datasetName: transcodes
  additionalStorages: []
