image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  pullPolicy: IfNotPresent
  tag: v8.7.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

esConfig:
  password: ''
  heapSize: 512m
  nodeName: elastic_search_node
  additionalEnvs: []

# Not user configurable
esRunAs:
  user: 1000
  group: 1000

esNetwork:
  httpPort: 30000
  hostNetwork: false
  certificateID: ''

esStorage:
  data:
    type: ixVolume
    hostPath: ''
    datasetName: data
