image:
  repository: ich777/steamcmd
  pullPolicy: IfNotPresent
  tag: palworld

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

palworldConfig:
  adminPassword: ''
  serverName: TrueNAS Palworld Server
  serverDescription: Palworld Server running on TrueNAS
  serverPassword: ''
  backup:
    enabled: false
    interval: 60
    keep: 3
  gameParams:
    - EpicApp=PalServer
  gameParamsExtra:
    - -useperfthreads
    - -NoAsyncLoadingThread
    - -UseMultithreadForDS
  updatePublicIP: false
  validate: false
  username: ''
  password: ''
  additionalEnvs: []

palworldID:
  user: 568
  group: 568

palworldNetwork:
  serverPort: 38211
  rconPort: 38212
  hostNetwork: false

palworldStorage:
  steamcmd:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  server:
    type: ixVolume
    ixVolumeConfig:
      datasetName: storage
  additionalStorages: []
