image:
  repository: wordpress
  pullPolicy: IfNotPresent
  tag: 6.3.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

wpConfig:
  additionalEnvs: []

wpNetwork:
  webPort: 30040

wpStorage:
  data:
    type: ixVolume
    datasetName: data
  mariadbData:
    type: ixVolume
    datasetName: mariadbData
  mariadbBackup:
    type: ixVolume
    datasetName: mariadbBackup
  additionalStorages: []
