image:
  repository: ghcr.io/onedr0p/radarr
  pullPolicy: IfNotPresent
  tag: 5.8.3.8933

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

radarrConfig:
  instanceName: Radarr
  additionalEnvs: []
radarrNetwork:
  webPort: 30025
  hostNetwork: false
radarrRunAs:
  user: 568
  group: 568
radarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
