image:
  repository: ghcr.io/benphelps/homepage
  pullPolicy: IfNotPresent
  tag: v0.6.29

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

homepageConfig:
  additionalEnvs: []

homepageNetwork:
  webPort: 30054
  hostNetwork: false

homepageStorage:
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []
