name: plex
description: Plex is a media server that allows you to stream your media to any Plex client.
annotations:
  title: Plex
type: application
version: 2.0.0
apiVersion: v2
appVersion: 1.32.8.7639
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://plex.tv/
icon: https://media.sys.truenas.net/apps/plex/icons/icon.png
sources:
  - https://plex.tv/
  - https://github.com/truenas/charts/tree/master/charts/plex
  - https://hub.docker.com/r/plexinc/pms-docker/
keywords:
  - plex
