giteaStorage:
  data:
    type: pvc
  config:
    type: pvc
  pgData:
    type: pvc
  pgBackup:
    type: emptyDir
    emptyDirConfig:
      medium: ""
      size: ""

giteaNetwork:
  rootURL: http://localhost:30000
  externalSshPort: 22
