image:
  pullPolicy: IfNotPresent
  repository: plexinc/pms-docker
  tag: 1.32.8.7639-fb6452ebf
plexPassImage:
  pullPolicy: IfNotPresent
  repository: plexinc/pms-docker
  tag: plexpass

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

plexID:
  user: 568
  group: 568

plexConfig:
  imageSelector: image
  claim: ''
  additionalEnvs: []

plexNetwork:
  webPort: 30003
  hostNetwork: false

plexStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  transcode:
    type: ixVolume
    ixVolumeConfig:
      datasetName: transcode
  additionalStorages: []

plexGPU: {}
