appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
  data:
    emptyDir: true
    mountPath: /data
  shared:
    emptyDir: true
    mountPath: shared
  shared-logs:
    emptyDir: true
    mountPath: /config/Library/Application Support/Plex Media Server/Logs
  transcode:
    emptyDir: true
    mountPath: /transcode
claimToken: ''
dnsConfig:
  options: []
emptyDirVolumes: true
enablePlexPass: false
environmentVariables: []
extraAppVolumeMounts:
- hostPath: /mnt/extras/hello
  mountPath: /mnt/extras
  readOnly: true
gpuConfiguration: {}
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: plexinc/pms-docker
  tag: 1.31.1.6733-bc0674160
plexServiceTCP:
  port: 32400
timezone: Etc/UTC
updateStrategy: Recreate
