image:
  repository: ghcr.io/mealie-recipes/mealie
  pullPolicy: IfNotPresent
  tag: v1.10.2

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

mealieConfig:
  allowSignup: true
  defaultGroup: Home
  defaultAdminEmail: ''
  defaultAdminPassword: ''
  baseURL: ''
  additionalEnvs: []

mealieRunAs:
  user: 568
  group: 568

mealieNetwork:
  webPort: 31001
  hostNetwork: false

mealieStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `mealie`
      - Username: `mealie`
      - Password: `{{ .Values.mealieDbPass }}`
      - Host:     `{{ .Values.mealieDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "mealieDbPass" }}
    {{- $_ := unset .Values "mealieDbHost" }}
