name: netdata
description: Real-time performance monitoring, done right!
annotations:
  title: Netdata
type: application
version: 2.0.13
apiVersion: v2
appVersion: v1.46.2
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.netdata.cloud/
icon: https://media.sys.truenas.net/apps/netdata/icons/icon.png
sources:
  - https://www.netdata.cloud/
  - https://github.com/netdata/helmchart
  - https://hub.docker.com/r/netdata/netdata
  - https://github.com/netdata/netdata
keywords:
  - alerting
  - metric
  - monitoring
