image:
  pullPolicy: IfNotPresent
  repository: netdata/netdata
  tag: v1.46.2

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

podOptions:
  dnsConfig:
    options: []

netdataConfig:
  additionalEnvs: []

netdataNetwork:
  webPort: 20489

netdataStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  cache:
    type: ixVolume
    ixVolumeConfig:
      datasetName: cache
  lib:
    type: ixVolume
    ixVolumeConfig:
      datasetName: lib
  additionalStorages: []
