name: minio
description: High Performance, Kubernetes Native Object Storage
annotations:
  title: MinIO
type: application
version: 1.7.24
apiVersion: v2
appVersion: '2023-03-13'
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://min.io
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
sources:
  - https://github.com/minio/minio
  - https://github.com/minio/charts
keywords:
  - storage
  - object-storage
  - S3
