image:
  repository: roundcube/roundcubemail
  pullPolicy: IfNotPresent
  tag: 1.6.7-apache

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

roundcubeConfig:
  defaultHost: ''
  defaultPort: 143
  smtpServer: ''
  smtpPort: 587
  skin: elastic
  plugins:
    - archive
    - zipdownload
  aspellDicts: []
  uploadMaxSize: 5
  additionalEnvs: []

roundcubeNetwork:
  webPort: 31007

roundcubeStorage:
  html:
    type: ixVolume
    ixVolumeConfig:
      datasetName: html
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  temps:
    type: ixVolume
    ixVolumeConfig:
      datasetName: temps
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `roundcube`
      - Username: `roundcube`
      - Password: `{{ .Values.roundcubeDbPass }}`
      - Host:     `{{ .Values.roundcubeDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "roundcubeDbPass" }}
    {{- $_ := unset .Values "roundcubeDbHost" }}
