image:
  repository: ghcr.io/onedr0p/prowlarr-develop
  pullPolicy: IfNotPresent
  tag: 1.20.1.4603

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

prowlarrConfig:
  instanceName: Prowlarr
  additionalEnvs: []

prowlarrNetwork:
  webPort: 30050
  hostNetwork: false

prowlarrRunAs:
  user: 568
  group: 568

prowlarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
