image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: 1.50.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

n8nConfig:
  webHost: localhost
  additionalEnvs: []

n8nRunAs:
  user: 568
  group: 568

n8nNetwork:
  webPort: 30068
  certificateID:
  hostNetwork: false

n8nStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup
  additionalStorages: []

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `n8n`
      - Username: `n8n`
      - Password: `{{ .Values.n8nDbPass }}`
      - Host:     `{{ .Values.n8nDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "n8nDbPass" }}
    {{- $_ := unset .Values "n8nDbHost" }}
