image:
  repository: bitnami/redis
  pullPolicy: IfNotPresent
  tag: 7.2.5

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

redisConfig:
  allowEmptyPassword: false
  password: ''
  additionalEnvs: []

redisNetwork:
  hostNetwork: false
  redisPort: 30036

redisStorage:
  data:
    type: ixVolume
    datasetName: data
