image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.43.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

autobrrConfig:
  additionalEnvs: []

autobrrNetwork:
  webPort: 30051
  hostNetwork: false

autobrrRunAs:
  user: 568
  group: 568

autobrrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
