image:
  repository: jc21/nginx-proxy-manager
  pullPolicy: IfNotPresent
  tag: 2.11.3
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
npmConfig:
  additionalEnvs: []
npmNetwork:
  webPort: 30020
  httpPort: 30021
  httpsPort: 30022
npmID:
  user: 568
  group: 568
npmStorage:
  data:
    type: ixVolume
    datasetName: data
  certs:
    type: ixVolume
    datasetName: certs
notes:
  custom: |
    Default credentials:
    -  username: admin@example.com
    -  password: changeme
