image:
  repository: tailscale/tailscale
  pullPolicy: IfNotPresent
  tag: v1.68.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

tailscaleConfig:
  authkey: ''
  hostname: ''
  advertiseRoutes: []
  advertiseExitNode: false
  userspace: true
  acceptDns: false
  authOnce: true
  extraArgs: []
  extraDaemonArgs: []
  additionalEnvs: []

tailscaleNetwork:
  hostNetwork: false
