name: netdata
description: Real-time performance monitoring, done right!
annotations:
  title: Netdata
type: application
version: 1.0.40
apiVersion: v2
appVersion: v1.44.1
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://www.netdata.cloud/
icon: https://media.sys.truenas.net/apps/netdata/icons/icon.png
sources:
  - https://github.com/netdata/helmchart
  - https://github.com/netdata/netdata
keywords:
  - alerting
  - metric
  - monitoring
