name: collabora
description: Collabora is a collaborative online office suite based on LibreOffice
  technology
annotations:
  title: Collabora
type: application
version: 2.0.19
apiVersion: v2
appVersion: 24.04.5.1.1
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.collaboraoffice.com/
icon: https://media.sys.truenas.net/apps/collabora/icons/icon.png
sources:
  - https://www.collaboraoffice.com/
  - https://github.com/CollaboraOnline/online
  - https://hub.docker.com/r/collabora/code
keywords:
  - office
  - documents
  - productivity
