n8nNetwork:
  webPort: 31000

n8nStorage:
  data:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/data
  pgData:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/pgData
  pgBackup:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/pgBackup
