image:
  repository: benbusby/whoogle-search
  pullPolicy: IfNotPresent
  tag: 0.9.3

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

whoogleConfig:
  redirects: []
  additionalEnvs: []

whoogleNetwork:
  webPort: 30098
  hostNetwork: false

whoogleStorage:
  additionalStorages: []
