image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

controllers:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

key1: value1
key2: 80
key3: pair
key4: value2
key5: 81
key6: false

secrets:
  kv-test:
    enabled: true
    data:
      key: "{{ .Values.key1 }}"
      key1: "{{ .Values.key4 }}"
      key2: "{{ .Values.key5 }}"
      key3: "{{ .Values.key6 }}"

  file-test:
    enabled: true
    data:
      nginx.conf2: |
        alias {{ .Values.key3 }}
        listen {{ .Values.key2 }}
        function {
          # some json
          "key": {
            "key2": "value",
            "key3": "value2"
          }
        }
