appVolumeMounts:
  data:
    emptyDir: true
    mountPath: /app/config
  identity:
    emptyDir: true
    mountPath: /app/identity
authToken: user:sasjkadkjhakdlaskdlkajsd
dnsConfig:
  options: []
domainAddress: localhost
email: user@example.com
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts: []
terminationGracePeriod: 120
identityCreationMountPath: /root/.local/share/storj/identity/storagenode
nodePort: 30002
runAsGroup: 568
runAsUser: 568
storageSize: 500
wallet: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
webPort: 30000
zksync: true
zksyncEra: true
