image:
  repository: gotson/komga
  pullPolicy: IfNotPresent
  tag: 1.11.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

komgaConfig:
  additionalEnvs: []

komgaNetwork:
  webPort: 30048
  hostNetwork: false

komgaRunAs:
  user: 568
  group: 568

komgaStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
