image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.8.13

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

jellyfinConfig:
  publishedServerUrl: ''
  additionalEnvs: []
jellyfinGPU: {}
jellyfinNetwork:
  webPort: 30013
  hostNetwork: false
jellyfinRunAs:
  user: 568
  group: 568
jellyfinStorage:
  config:
    type: ixVolume
    datasetName: config
  cache:
    type: ixVolume
    datasetName: cache
  transcodes:
    type: ixVolume
    datasetName: transcodes
    medium: ''
    size: ''
  additionalStorages: []
