name: elastic-search
description: Elasticsearch is the distributed, RESTful search and analytics engine
  at the heart of the Elastic Stack.
annotations:
  title: Elastic Search
type: application
version: 1.0.25
apiVersion: v2
appVersion: 8.10.3
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.1.1
home: https://www.elastic.co
icon: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt280217a63b82a734/6202d3378b1f312528798412/elastic-logo.svg
sources:
  - https://www.elastic.co/
  - https://github.com/truenas/charts/tree/master/charts/elastic-search
  - https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html#docker-configuration-methods
keywords:
  - search
  - elastic
