{{ include "common.storage.hostPathValidate" .Values }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-emby
  labels:
    app.kubernetes.io/name: {{ template "common.names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ (default 1 .Values.replicas) }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template: {{ include "common.deployment.pod.metadata" . | nindent 4 }}
    spec:
    {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
      hostname: {{ template "common.names.fullname" . }}
      {{- if hasKey .Values "global" }}
        {{- if hasKey .Values.global "ixChartContext" }}
          {{- if .Values.global.ixChartContext.addNvidiaRuntimeClass }}
      runtimeClassName: {{ .Values.global.ixChartContext.nvidiaRuntimeClassName }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ include "common.resources.limitation" . | nindent 10 }}
          {{ include "common.containers.imageConfig" .Values.image | nindent 10 }}
          volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
            {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
            - name: extrappvolume-{{ $index }}
              mountPath: {{ $hostPathConfiguration.mountPath }}
              {{ if $hostPathConfiguration.readOnly }}
              readOnly: {{ $hostPathConfiguration.readOnly }}
              {{ end }}
            {{ end }}
          ports:
          - name: emby
            protocol: TCP
            containerPort: 8096
          {{- if not .Values.hostNetwork }}
            hostPort: null
          {{- end }}
          - name: emby-dlna
            protocol: UDP
            containerPort: 1900
          {{- if not .Values.hostNetwork }}
            hostPort: null
          {{- end }}
          - name: emby-lnd
            protocol: UDP
            containerPort: 7359
          {{- if not .Values.hostNetwork }}
            hostPort: null
          {{- end }}
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{ $envList := (default list .Values.environmentVariables) }}
            {{ if and .Values.gpuConfiguration (hasKey .Values.gpuConfiguration "nvidia.com/gpu") (gt (get .Values.gpuConfiguration "nvidia.com/gpu" | toDecimal) 0) }}
            {{ $envList = mustAppend $envList (dict "name" "NVIDIA_DRIVER_CAPABILITIES" "value" "all") }}
            {{ end }}
            {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /emby/System/Ping
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /emby/System/Ping
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /emby/System/Ping
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 60
            successThreshold: 1
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
        {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
        - name: extrappvolume-{{ $index }}
          hostPath:
            path: {{ $hostPathConfiguration.hostPath }}
        {{ end }}
