name: emby
description: Emby Server
annotations:
  title: Emby Server
type: application
version: 1.0.30
apiVersion: v2
appVersion: 4.7.14.0
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://emby.media/
icon: https://media.sys.truenas.net/apps/emby/icons/icon.png
sources:
  - https://hub.docker.com/r/emby/embyserver
keywords:
  - emby
  - media
