image:
  repository: qmcgaw/ddns-updater
  pullPolicy: IfNotPresent
  tag: v2.7.0

ci: false

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

ddnsConfig:
  period: 5m
  backupPeriod: 24h
  updateCooldownPeriod: 5m
  httpTimeout: 10s
  shoutrrrAddresses: []
  publicIpDnsTimeout: 3s
  publicIpDnsProviders:
    - provider: all
  publicIpHttpProviders:
    - provider: all
      custom: ''
  publicIpv4HttpProviders:
    - provider: all
      custom: ''
  publicIpv6HttpProviders:
    - provider: all
      custom: ''
  publicIpFetchers:
    - provider: all
  config: []
    # - provider: cloudflare
    #   host: "@"
    #   domain: example.com
    #   ipVersion: ""
    #   cfZoneID: asd
    #   cfTtl: 1
    #   cfProxied: false
    #   cfToken: asd

  additionalEnvs: []
ddnsNetwork:
  webPort: 30007
  hostNetwork: false
ddnsRunAs:
  user: 568
  group: 568
ddnsStorage:
  data:
    type: ixVolume
    datasetName: data
