name: elastic-search
description: Elasticsearch is the distributed, RESTful search and analytics engine
  at the heart of the Elastic Stack.
annotations:
  title: Elastic Search
type: application
version: 1.1.21
apiVersion: v2
appVersion: 8.14.2
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.elastic.co
icon: https://media.sys.truenas.net/apps/elastic-search/icons/icon.svg
sources:
  - https://www.elastic.co/
  - https://github.com/truenas/charts/tree/master/charts/elastic-search
  - https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html#docker-configuration-methods
keywords:
  - search
  - elastic
