image:
  repository: searxng/searxng
  pullPolicy: IfNotPresent
  tag: 2024.11.29-cf034488d

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

searxngConfig:
  instanceName: SearXNG
  additionalEnvs: []

searxngNetwork:
  webPort: 30053
  hostNetwork: false

searxngStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
