image:
  repository: haveagitgat/tdarr
  pullPolicy: IfNotPresent
  tag: 2.22.01

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
tdarrConfig:
  nodeName: ''
  internalNode: true
  serverIP: 0.0.0.0
  additionalEnvs: []
tdarrNetwork:
  webPort: 30028
  serverPort: 30029
tdarrGPU: {}
tdarrID:
  user: 568
  group: 568
tdarrStorage:
  server:
    type: ixVolume
    ixVolumeConfig:
      datasetName: server
  configs:
    type: ixVolume
    ixVolumeConfig:
      datasetName: configs
  logs:
    type: ixVolume
    ixVolumeConfig:
      datasetName: logs
  transcodes:
    type: ixVolume
    ixVolumeConfig:
      datasetName: transcodes
  additionalStorages: []
