image:
  repository: prometheus/kubo
  pullPolicy: IfNotPresent
  tag: v0.19.0
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
prometheusConfig:
  retentionTime: 15d
  retentionSize: ""
  walCompression: true
  additionalEnvs: []
  additionalArgs: []
prometheusNetwork:
  apiPort: 30000
  hostNetwork: false
prometheusRunAs:
  user: 568
  group: 568
prometheusStorage:
  data:
    type: ixVolume
    hostPath: ''
    datasetName: data
  config:
    type: ixVolume
    hostPath: ''
    datasetName: config
