name: photoprism
description: AI-powered app for browsing, organizing & sharing your photo collection.
annotations:
  title: PhotoPrism
type: application
version: 2.0.8
apiVersion: v2
appVersion: '240531'
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://photoprism.app/
icon: https://media.sys.truenas.net/apps/photoprism/icons/icon.svg
sources:
  - https://photoprism.app/
  - https://github.com/truenas/charts/tree/master/charts/photoprism
keywords:
  - media
