name: minio
description: High Performance, Kubernetes Native Object Storage
annotations:
  title: MinIO
type: application
version: 2.0.27
apiVersion: v2
appVersion: 2024-12-18T13-15-44Z
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://min.io
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
sources:
  - https://github.com/minio/minio
keywords:
  - storage
  - object-storage
  - S3
