image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: 0.13.2

tensorrtImage:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: 0.13.2-tensorrt

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

frigateConfig:
  imageSelector: image
  mountUSBBus: false
  additionalEnvs: []

frigateNetwork:
  hostNetwork: false
  # Port numbers ignored if hostNetwork is true
  webPort: 30058
  enableRtmp: false
  rtmpPort: 30059
  enableRtsp: false
  rtspPort: 30060
  enableWebRtc: false
  webRtcPort: 30061

frigateGPU: {}

frigateStorage:
  media:
    type: ixVolume
    ixVolumeConfig:
      datasetName: media
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  cache:
    sizeGiB: 1
  shm:
    sizeMiB: 64
  additionalStorages: []
