name: syncthing
description: Syncthing is a continuous file synchronization program.
annotations:
  title: Syncthing
type: application
version: 2.0.8
apiVersion: v2
appVersion: 1.27.9
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://syncthing.net/
icon: https://media.sys.truenas.net/apps/syncthing/icons/icon.svg
sources:
  - https://syncthing.net
  - https://github.com/truenas/charts/tree/master/charts/syncthing
keywords:
  - storage
  - backup
