image:
  repository: ghcr.io/onedr0p/readarr-develop
  pullPolicy: IfNotPresent
  tag: 0.3.30.2576

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

readarrConfig:
  instanceName: Readarr
  additionalEnvs: []
readarrNetwork:
  webPort: 30045
  hostNetwork: false
readarrRunAs:
  user: 568
  group: 568
readarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
