image:
  repository: fallenbagel/jellyseerr
  pullPolicy: IfNotPresent
  tag: 1.9.2

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

jellyseerrConfig:
  additionalEnvs: []

jellyseerrNetwork:
  webPort: 30042
  hostNetwork: false

jellyseerrRunAs:
  user: 568
  group: 568

jellyseerrStorage:
  config:
    type: ixVolume
    datasetName: config
