apiVersion: v2
appVersion: v1.68.2
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: Share your storage on the internet and earn.
home: https://www.storj.io/
icon: https://assets-global.website-files.com/602eda09fc78afc76e9706b6/60917835a05862243e7de9af_logo.svg
keywords:
- storage
- dapps
- networking
- financial
name: storj
version: 1.0.5
