appVolumeMounts:
  data:
    emptyDir: true
    mountPath: /app/config
  identity:
    emptyDir: true
    mountPath: /app/identity
authToken: user:sasjkadkjhakdlaskdlkajsd
dnsConfig:
  options: []
domainAddress: localhost
email: user@example.com
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts: []
identityCreationMountPath: /root/.local/share/storj/identity/storagenode
image:
  pullPolicy: IfNotPresent
  repository: storjlabs/storagenode
  tag: ab9cb72f8-v1.67.1-go1.18.8
nodePort: 30002
runAsGroup: 568
runAsUser: 568
storageSize: 500
wallet: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
webPort: 30001
