image:
  repository: ghcr.io/onedr0p/sonarr
  pullPolicy: IfNotPresent
  tag: 4.0.6.1805

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

sonarrConfig:
  instanceName: Sonarr
  additionalEnvs: []
sonarrNetwork:
  webPort: 30027
  hostNetwork: false
sonarrRunAs:
  user: 568
  group: 568
sonarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
