image:
  repository: adguard/adguardhome
  tag: v0.107.52
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

adguardNetwork:
  webPort: 30004
  enableDHCP: false

# FIXME: See _adguard.tpl
# adguardRunAs:
#   user: 568
#   group: 568

adguardStorage:
  work:
    type: ixVolume
    datasetName: work
  conf:
    type: ixVolume
    datasetName: conf
