image:
  repository: ipfs/kubo
  pullPolicy: IfNotPresent
  tag: v0.19.0
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
ipfsConfig:
  additionalEnvs: []
ipfsNetwork:
  apiPort: 30000
  swarmPort: 30001
  gatewayPort: 30002
  hostNetwork: false
ipfsRunAs:
  user: 568
  group: 568
ipfsStorage:
  data:
    type: ixVolume
    hostPath: ''
    datasetName: data
  staging:
    type: ixVolume
    hostPath: ''
    datasetName: staging
