# -- (docs/README.md)
global:
  labels: {}
  annotations: {}
  minNodePort: 9000

# -- (docs/README.md)
fallbackDefaults:
  probeType: http
  serviceProtocol: tcp
  serviceType: ClusterIP
  persistenceType: emptyDir
  pvcRetain: false
  pvcSize: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  probeTimeouts:
    liveness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 2
    startup:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 60
      successThreshold: 1

# -- (docs/README.md)
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

bashImage:
  repository: bash
  tag: "4.4.23"
  pullPolicy: IfNotPresent

postgresImage:
  repository: postgres
  tag: "15.2"
  pullPolicy: IfNotPresent

mariadbImage:
  repository: mariadb
  tag: "10.6.14"
  pullPolicy: IfNotPresent

redisImage:
  repository: bitnami/redis
  tag: "7.0.11"
  pullPolicy: IfNotPresent

# -- (docs/README.md)
securityContext:
  container:
    PUID: 568
    UMASK: "002"
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add: []
      drop:
        - ALL
  pod:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: []
    sysctls: []

# -- (docs/README.md)
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 50Mi
  NVIDIA_CAPS:
    - all

# -- (docs/README.md)
podOptions:
  enableServiceLinks: false
  hostNetwork: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  hostAliases: []
  tolerations: []
  runtimeClassName: ""
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 30

# -- (docs/notes.md)
notes:
  header: |
    # Welcome to TrueNAS SCALE
    Thank you for installing {{ .Chart.Annotations.title }} App.
  # custom: "{{ toYaml $.Values }}"
  custom: ""
  footer: |
    # Documentation
    Documentation for this app can be found at https://www.truenas.com/docs.
    # Bug reports
    If you find a bug in this app, please file an issue at https://ixsystems.atlassian.net

# -- Timezone used everywhere applicable
TZ: UTC

# -- (docs/workload/README.md)
workload: {}

# -- (docs/service/README.md)
service: {}

# -- (docs/persistence/README.md)
persistence: {}
  # shared:
  #   enabled: false # TODO: Enable by default?
  #   type: emptyDir
  #   mountPath: /shared
  #   targetSelectAll: true
  # varlogs:
  #   enabled: false # TODO: Enable by default?
  #   type: emptyDir
  #   mountPath: /var/logs
  #   targetSelectAll: true
  # tmp:
  #   enabled: false # TODO: Enable by default?
  #   type: emptyDir
  #   mountPath: /tmp
  #   targetSelectAll: true
  # devshm:
  #   enabled: false # TODO: Enable by default?
  #   type: emptyDir
  #   mountPath: /dev/shm
  #   targetSelectAll: true

# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfiguration: []
# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfigurationNames: []
# -- Injected from SCALE middleware
# Only for reference here
ixCertificates: []
# -- Injected from SCALE middleware
# Only for reference here
ixVolumes: []

# -- (docs/imagePullSecrets.md)
imagePullSecret: []

# -- (docs/configmap.md)
configmap: {}

# -- (docs/secret.md)
secret: {}

# -- (docs/serviceAccount.md)
serviceAccount: {}

# -- (docs/rbac.md)
rbac: {}

# -- (docs/scaleExternalInterface.md)
scaleExternalInterface: []

# -- (docs/scaleCertificate.md)
scaleCertificate: {}

# -- (docs/scaleGPU.md)
scaleGPU: []

# TODO:
portal: {}
