name: wg-easy
description: WG-Easy is the easiest way to install & manage WireGuard!
annotations:
  title: WG Easy
type: application
version: 2.0.19
apiVersion: v2
appVersion: '13'
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://github.com/WeeJeWel/wg-easy
icon: https://media.sys.truenas.net/apps/wg-easy/icons/icon.png
sources:
  - https://github.com/WeeJeWel/wg-easy
  - https://github.com/truenas/charts/tree/master/charts/wg-easy
keywords:
  - wireguard
  - network
  - vpn
