image:
  repository: rustdesk/rustdesk-server
  pullPolicy: IfNotPresent
  tag: 1.1.11-1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

rustConfig:
  allowOnlyEncryptedConnections: false
  additionalRelayServers: []
  additionalEnvs: []

rustNetwork:
  natTypeTestPort: 21115
  idRegHolePunchPort: 21116
  relayPort: 21117
  enableWebClientPorts: true
  serverWebClientsPort: 21118
  relayWebClientsPort: 21119
  hostNetwork: false

rustRunAs:
  user: 568
  group: 568

rustStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
