image:
  repository: ghcr.io/plankanban/planka
  pullPolicy: IfNotPresent
  tag: 1.19.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

plankaConfig:
  defaultAdminEmail: ''
  defaultAdminName: ''
  defaultAdminPassword: ''
  defaultAdminUsername: ''
  trustProxy: false
  baseURL: http://localhost:30062
  additionalEnvs: []

plankaNetwork:
  webPort: 30062
  hostNetwork: false

plankaStorage:
  avatars:
    type: ixVolume
    ixVolumeConfig:
      datasetName: avatars
  backgroundImages:
    type: ixVolume
    ixVolumeConfig:
      datasetName: bg-img
  attachments:
    type: ixVolume
    ixVolumeConfig:
      datasetName: attachments
  additionalStorages: []
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `planka`
      - Username: `planka`
      - Password: `{{ .Values.plankaDbPass }}`
      - Host:     `{{ .Values.plankaDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "plankaDbPass" }}
    {{- $_ := unset .Values "plankaDbHost" }}
