name: storj
description: Share your storage on the internet and earn.
annotations:
  title: Storj
type: application
version: 2.0.1
apiVersion: v2
appVersion: v1.68.2
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.storj.io
icon: https://media.sys.truenas.net/apps/storj/icons/icon.svg
sources:
  - https://www.storj.io
  - https://github.com/truenas/charts/tree/master/charts/storj
keywords:
  - storage
  - dapps
  - networking
  - financial
