image:
  repository: httpd
  pullPolicy: IfNotPresent
  tag: 2.4.61

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

webdavConfig:
  authType: none
  username: ''
  password: ''
  additionalBrowserMatches: []
  additionalEnvs: []
webdavNetwork:
  hostNetwork: false
  http: true
  httpPort: 30034
  https: false
  httpsPort: 30035
  certificateID:
webdavRunAs:
  user: 568
  group: 568
webdavStorage:
  shares: []
