image:
  pullPolicy: IfNotPresent
  repository: weejewel/wg-easy
  tag: "7"

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

podOptions:
  dnsConfig:
    options: []

wgNetwork:
  udpPort: 30057
  webPort: 30058
  hostNetwork: false

wgConfig:
  host: ''
  password: ''
  keepAlive: 0
  clientMTU: 1420
  clientAddressRange: 10.8.0.x
  clientDNSServer: "1.1.1.1"
  allowedIPs: []
  additionalEnvs: []

wgStorage:
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []
