image:
  repository: ghcr.io/onedr0p/radarr
  pullPolicy: IfNotPresent
  tag: 4.4.4.7068

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

radarrConfig:
  instanceName: Radarr
  additionalEnvs: []
radarrNetwork:
  webPort: 30000
  hostNetwork: false
radarrRunAs:
  user: 568
  group: 568
radarrStorage:
  config:
    type: ixVolume
    hostPath: ''
    datasetName: config
  additionalStorages: []
