image:
  repository: drakkan/sftpgo
  pullPolicy: IfNotPresent
  tag: v2.6.2
pluginsImage:
  repository: drakkan/sftpgo
  pullPolicy: IfNotPresent
  tag: v2.6.2-plugins

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

sftpgoConfig:
  imageSelector: image
  graceTime: 60
  additionalEnvs: []

sftpgoNetwork:
  hostNetwork: false
  certificateID:
  webPort: 30086
  webdavdServices: []
  sftpdServices: []
  ftpdServices: []
  ftpdPassivePortRange:
    start: 50000
    end: 50001

sftpgoRunAs:
  user: 568
  group: 568

sftpgoStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  backups:
    type: ixVolume
    ixVolumeConfig:
      datasetName: backups
  additionalStorages: []
