image:
  repository: drakkan/sftpgo
  pullPolicy: IfNotPresent
  tag: v2.5.4
pluginsImage:
  repository: drakkan/sftpgo
  pullPolicy: IfNotPresent
  tag: v2.5.4-plugins

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

sftpgoConfig:
  imageSelector: image
  graceTime: 60
  additionalEnvs: []

sftpgoNetwork:
  hostNetwork: false
  webPort: 30086
  sftpdServices:
    - enabled: true
      port: 30087
    - enabled: true
      port: 30088
  ftpdServices:
    - enabled: true
      port: 30087
    - enabled: true
      port: 30088
  webdavServices:
    - enabled: true
      port: 30087
    - enabled: true
      port: 30088

sftpgoRunAs:
  user: 568
  group: 568

sftpgoStorage:
  config:
    type: ixVolume
    datasetName: config
  data:
    type: ixVolume
    datasetName: data
  backups:
    type: ixVolume
    datasetName: backups
  additionalStorages: []
