image:
  repository: actualbudget/actual-server
  pullPolicy: IfNotPresent
  tag: 24.7.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

actualConfig:
  additionalEnvs: []

actualNetwork:
  webPort: 31012
  certificateID:
  hostNetwork: false

actualRunAs:
  user: 568
  group: 568

actualStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
