image:
  repository: ghcr.io/onedr0p/tautulli
  pullPolicy: IfNotPresent
  tag: 2.13.4

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

tautulliConfig:
  additionalEnvs: []

tautulliNetwork:
  webPort: 30047
  hostNetwork: false

tautulliRunAs:
  user: 568
  group: 568

tautulliStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
