image:
  repository: ghcr.io/onedr0p/bazarr
  pullPolicy: IfNotPresent
  tag: 1.5.1

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

bazarrConfig:
  additionalEnvs: []

bazarrNetwork:
  webPort: 30046
  hostNetwork: false

bazarrRunAs:
  user: 568
  group: 568

bazarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
