name: collabora
description: |
  Collabora Online Development Edition \u2013 an awesome, Online Office
  suite image suitable for home use.
annotations:
  title: Collabora
type: application
version: 1.2.19
apiVersion: v2
appVersion: 23.05.5.1.1
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://github.com/CollaboraOnline/online
icon: https://avatars.githubusercontent.com/u/22418908?s=200&v=4
sources:
  - https://github.com/CollaboraOnline/online.git
  - https://hub.docker.com/r/collabora/code
keywords:
  - office
  - documents
  - productivity
